spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eventhub}
    username: ${DB_USERNAME:eventhub}
    password: ${DB_PASSWORD:eventhub}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    com.tcs.eventhub: INFO
